spring:
  application:
    name: blogyg-server-monitor
  zipkin:
    base-url: http://blogyg:8777

server:
  port: 9002

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream


eureka:
  client:
    serviceUrl:
      defaultZone: http://blogyg:8111/eureka/
